# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'again.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(594, 293)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 70, 401, 51))
        self.label.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 9pt \"黑体\";\n"
"font: 12pt \"Adobe Arabic\";")
        self.label.setObjectName("label")
        self.B_again = QtWidgets.QPushButton(self.centralwidget)
        self.B_again.setGeometry(QtCore.QRect(410, 170, 93, 28))
        self.B_again.setObjectName("B_again")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 594, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "密码错误"))
        self.label.setText(_translate("MainWindow", "您的输入有错误！点击“返回”按钮重新输入"))
        self.B_again.setText(_translate("MainWindow", "返回"))
